import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import {i18nConfig} from '@/i18nConfig';
import { dir } from 'i18next';
import { cn } from "@/lib/utils"
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Darbuk",
  description: "Generated by Ivaylo",
};

export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode,
  params: { locale: any },
}>) {
  return (
    <html lang={locale} dir={dir(locale)}>
      <head>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </head>
       <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  );
}
